version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
    networks:
      - bridge
    volumes:
      - mongo_data:/data/db
  
  orderapi:
    image: orderapi
    container_name: orderapi
    restart: always
    ports:
      - "3001:3001"
    networks:
      - bridge
    volumes:
      - orderapi_data:/usr/share/orderapi/data
    environment:
      - DEBUG=1
      - DB_HOST=mongo
    depends_on:
      - mongo
  
  staticserver:
    image: staticserver
    container_name: staticserver
    restart: always
    ports:
      - "3000:3000"
    networks:
      - bridge
    volumes:
      - staticserver_data:/usr/share/staticserver/data
    environment:
      - DEBUG=1
      - DB_HOST=mongo
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - bridge
    depends_on:
      - orderapi
      - staticserver

networks:
  bridge:
    driver: bridge

volumes:
  mongo_data:
  orderapi_data:
  staticserver_data: